### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by Lexinek** [Zenify/DoctrineMethodsHydrator#13]
```php
    /**
     * @inject
     * @var Zenify\DoctrineMethodsHydrator\Contract\MethodsHydratorInterface
     */
    public $methodsHydrator;
```

*Zenify\DoctrineMethodsHydrator\Contract\MethodsHydratorInterface* does not exist, using *Zenify\DoctrineMethodsHydrator\MethodsHydrator* instead works.

**Comment by TomasVotruba** [comment]
Do you use last version?

**Comment by Lexinek** [comment]
That could be it, im using 5.0.2, since we dont have access to PHP 5.6 on server yet.

**Comment by TomasVotruba** [comment]
Pick a tag for version you are using then. There is switch with "master" on it.

**Comment by TomasVotruba** [comment]
Here: https://github.com/Zenify/DoctrineMethodsHydrator/tree/v5.0.2
