### ISSUE TITLE
Is @persistent support possible?

### ISSUE THREAD

**Issue by JanMikes** [Zenify/DoctrineMethodsHydrator#14]
I love this package, though, i have to use some workarounds when i need persistent parameters.
Is it even possible to have stored entity in `@persistent` annotated property  instead of id?

``` php
/** @var Book @persistent */
public $book;

public function renderDetail(Book $book)
{
  $book; // instanceof Book
  $this->book; // integer
}
```

Would it be possible to have instance of Book as well in `$this->book`?

**Comment by TomasVotruba** [comment]
Persistent parameter and method arguments have no common ground in this.

What's your goal?

**Comment by TomasVotruba** [comment]
Btw, I'm looking for a maintainer. Would you like to take over this project?

**Comment by enumag** [comment]
@Lexinek I have an alternative package that will pretty much replace this one when released. And it has the feature you're looking for. It's not public yet but I could give you a beta access. Send me an e-mail if interested.

**Comment by JanMikes** [comment]
Hi @enumag i was thinking more deeply about persistent parameters and i am still fighting with myself, not sure if it is good approach or not. 

I usually needed entity in property, when passing to a component factory, which was expecting instance of entity as its argument.

Until now i was using this kind of workaround:

``` php

/** @persistent */
public $entity;

private $myEntity;

public function actionXy(Entity $entity)
{
    $this->myEntity = $entity;
}


protected function createComponentXy()
{
    $this->factory->create($this->myEntity);
}
```

Anyways for sure i will contact you and i can give your package a try.

**Comment by enumag** [comment]
When I need to pass an entity to component I don't use persistent parameters. Here is my approach:

``` php
public function actionXy(Entity $entity)
{
}

protected function createComponentXy()
{
    return $this->factory->create($this->getParameter('entity'));
}
```

What do you think about it? Of course this as well is only possible with my EntityLoader package.

**Comment by JanMikes** [comment]
But you have defined persistent parameter `$entity` and difference is only in accessing its value by `$presenter->getParameter()` (which is overloaded i guess?) instead of accessing it directly `$this->entity` right?

I have in my mind so many usecases, where it would be better to have entity stored directly in persistent parameter, but im still not sure if it is even possible to desire and if it is not too much of black magic.

I will contact you via gitter/email and we can discuss, maybe together we will find perfect solution.

**Comment by enumag** [comment]
In my case the parameter is not persistent. It could be, I just had no reason to make it that way.

Anyway entities in persistent parameters are possible with my library as well.
